"""add face registration fields to student_profiles

Revision ID: d2b24c70b2c3
Revises: 628cf68fc50f
Create Date: 2025-05-18 08:34:38.727398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b24c70b2c3'
down_revision: Union[str, None] = '628cf68fc50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendances', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('student_profiles', sa.Column('is_face_registered', sa.Boolean(), nullable=True))
    op.add_column('student_profiles', sa.Column('face_image_url', sa.String(length=500), nullable=True))
    op.add_column('student_profiles', sa.Column('registration_complete', sa.Boolean(), nullable=True))
    op.add_column('student_profiles', sa.Column('section', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('rfid_tag', sa.String(length=100), nullable=True))
    op.add_column('student_profiles', sa.Column('last_face_update', sa.DateTime(), nullable=True))
    op.alter_column('student_profiles', 'face_encoding',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               postgresql_using='face_encoding::bytea')  # Add this USING clause
    op.create_index(op.f('ix_student_profiles_is_face_registered'), 'student_profiles', ['is_face_registered'], unique=False)
    op.create_index(op.f('ix_student_profiles_registration_complete'), 'student_profiles', ['registration_complete'], unique=False)
    op.create_index(op.f('ix_student_profiles_section'), 'student_profiles', ['section'], unique=False)
    op.create_unique_constraint(None, 'student_profiles', ['rfid_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='unique')
    op.drop_index(op.f('ix_student_profiles_section'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_registration_complete'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_is_face_registered'), table_name='student_profiles')
    op.alter_column('student_profiles', 'face_encoding',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('student_profiles', 'last_face_update')
    op.drop_column('student_profiles', 'rfid_tag')
    op.drop_column('student_profiles', 'section')
    op.drop_column('student_profiles', 'registration_complete')
    op.drop_column('student_profiles', 'face_image_url')
    op.drop_column('student_profiles', 'is_face_registered')
    op.alter_column('attendances', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
